external_components:
  - source: github://syssi/esphome-jk-bms@main
    refresh: 0s

ota:
  platform: esphome
  on_begin:
    then:
      - switch.turn_off: ble_client_switch0
      - logger.log: "BLE connection suspended for OTA update"
  on_end:
    then:
      - switch.turn_on: ble_client_switch0
      - logger.log: "BLE connection enabled after OTA update"

esp32_ble_tracker:
  scan_parameters:
    active: false

ble_client:
  - mac_address: ${bms_mac}
    id: client0

jk_bms_ble:
  - ble_client_id: client0
    protocol_version: ${bms_protocol}
    throttle: 5s
    id: bms0

binary_sensor:
  - platform: jk_bms_ble
    balancing:
      name: "BMS balancing"
    charging:
      name: "BMS charging"
    discharging:
      name: "BMS discharging"
#    heating:
      #name: "BMS heating"
    online_status:
      name: "BMS online status"

button:
  - platform: jk_bms_ble
    retrieve_settings:
      name: "BMS retrieve settings"
    retrieve_device_info:
      name: "BMS retrieve device info"

number:
  - platform: jk_bms_ble
    jk_bms_ble_id: bms0
    balance_trigger_voltage:
      name: "BMS balance trigger voltage"
    cell_count:
      name: "BMS cell count"
    total_battery_capacity:
      name: "BMS total battery capacity"
    cell_voltage_overvoltage_protection:
      name: "BMS cell voltage overvoltage protection"
    cell_voltage_overvoltage_recovery:
      name: "BMS cell voltage overvoltage recovery"
    cell_voltage_undervoltage_protection:
      name: "BMS cell voltage undervoltage protection"
    cell_voltage_undervoltage_recovery:
      name: "BMS cell voltage undervoltage recovery"
    balance_starting_voltage:
      name: "BMS balance starting voltage"
    voltage_calibration:
      name: "BMS voltage calibration"
    current_calibration:
      name: "BMS current calibration"
    power_off_voltage:
      name: "BMS power off voltage"
    max_balance_current:
      name: "BMS max balance current"
    max_charge_current:
      name: "BMS max charge current"
    max_discharge_current:
      name: "BMS max discharge current"
    charge_overcurrent_protection_delay:
      name: "BMS charge overcurrent protection delay"
    charge_overcurrent_protection_recovery_time:
      name: "BMS charge overcurrent protection recovery time"
    discharge_overcurrent_protection_delay:
      name: "BMS discharge overcurrent protection delay"
    discharge_overcurrent_protection_recovery_time:
      name: "BMS discharge overcurrent protection recovery time"
    short_circuit_protection_delay:
      name: "BMS short circuit protection delay"
    short_circuit_protection_recovery_time:
      name: "BMS short circuit protection recovery time"
    charge_overtemperature_protection:
      name: "BMS charge overtemperature protection"
    charge_overtemperature_protection_recovery:
      name: "BMS charge overtemperature protection recovery"
    discharge_overtemperature_protection:
      name: "BMS discharge overtemperature protection"
    discharge_overtemperature_protection_recovery:
      name: "BMS discharge overtemperature protection recovery"
    charge_undertemperature_protection:
      name: "BMS charge undertemperature protection"
    charge_undertemperature_protection_recovery:
      name: "BMS charge undertemperature protection recovery"
    power_tube_overtemperature_protection:
      name: "BMS power tube overtemperature protection"
    power_tube_overtemperature_protection_recovery:
      name: "BMS power tube overtemperature protection recovery"

sensor:
  - platform: jk_bms_ble
    jk_bms_ble_id: bms0
    min_cell_voltage:
      name: "BMS min cell voltage"
    max_cell_voltage:
      name: "BMS max cell voltage"
    min_voltage_cell:
      name: "BMS min voltage cell"
    max_voltage_cell:
      name: "BMS max voltage cell"
    delta_cell_voltage:
      name: "BMS delta cell voltage"
    average_cell_voltage:
      name: "BMS average cell voltage"
    cell_voltage_1:
      name: "BMS cell voltage 01"
    cell_voltage_2:
      name: "BMS cell voltage 02"
    cell_voltage_3:
      name: "BMS cell voltage 03"
    cell_voltage_4:
      name: "BMS cell voltage 04"
    cell_voltage_5:
      name: "BMS cell voltage 05"
    cell_voltage_6:
      name: "BMS cell voltage 06"
    cell_voltage_7:
      name: "BMS cell voltage 07"
    cell_voltage_8:
      name: "BMS cell voltage 08"
    cell_voltage_9:
      name: "BMS cell voltage 09"
    cell_voltage_10:
      name: "BMS cell voltage 10"
    cell_voltage_11:
      name: "BMS cell voltage 11"
    cell_voltage_12:
      name: "BMS cell voltage 12"
    cell_voltage_13:
      name: "BMS cell voltage 13"
    cell_voltage_14:
      name: "BMS cell voltage 14"
    cell_resistance_1:
      name: "BMS cell resistance 01"
    cell_resistance_2:
      name: "BMS cell resistance 02"
    cell_resistance_3:
      name: "BMS cell resistance 03"
    cell_resistance_4:
      name: "BMS cell resistance 04"
    cell_resistance_5:
      name: "BMS cell resistance 05"
    cell_resistance_6:
      name: "BMS cell resistance 06"
    cell_resistance_7:
      name: "BMS cell resistance 07"
    cell_resistance_8:
      name: "BMS cell resistance 08"
    cell_resistance_9:
      name: "BMS cell resistance 09"
    cell_resistance_10:
      name: "BMS cell resistance 10"
    cell_resistance_11:
      name: "BMS cell resistance 11"
    cell_resistance_12:
      name: "BMS cell resistance 12"
    cell_resistance_13:
      name: "BMS cell resistance 13"
    cell_resistance_14:
      name: "BMS cell resistance 14"
    total_voltage:
      name: "BMS total voltage"
    current:
      name: "BMS current"
#    heating_current:
#      name: "BMS heating current"
    power:
      name: "BMS power"
    charging_power:
      name: "BMS charging power"
    discharging_power:
      name: "BMS discharging power"
    temperature_sensor_1:
      name: "BMS temperature sensor 1"
    temperature_sensor_2:
      name: "BMS temperature sensor 2"
    temperature_sensor_3:
      name: "BMS temperature sensor 3"
    temperature_sensor_4:
      name: "BMS temperature sensor 4"
    power_tube_temperature:
      name: "BMS power tube temperature"
    balancing:
      name: "BMS balancing"
    state_of_charge:
      name: "BMS state of charge"
    capacity_remaining:
      name: "BMS capacity remaining"
    total_battery_capacity_setting:
      name: "BMS total battery capacity setting"
    charging_cycles:
      name: "BMS charging cycles"
    total_charging_cycle_capacity:
      name: "BMS total charging cycle capacity"
    total_runtime:
      name: "BMS total runtime"
    balancing_current:
      name: "BMS balancing current"
    errors_bitmask:
      name: "BMS errors bitmask"

switch:
  - platform: jk_bms_ble
    charging:
      name: "BMS charging"
    discharging:
      name: "BMS discharging"
    balancer:
      name: "BMS balancer"

  - platform: ble_client
    ble_client_id: client0
    id: ble_client_switch0
    name: "BMS enable bluetooth connection"

text_sensor:
  - platform: jk_bms_ble
    errors:
      name: "BMS errors"
    total_runtime_formatted:
      name: "BMS total runtime formatted"
